## Codebook
-----------
Here are all of the variables shared across the four surveys. I verified that the codes correspond to the same questions in each version. Some items, such as BNPL 4 represent multiple responses to a single question and thus take up more than one column.

**Dependent variables**
|BNPL1| In the past year, have you used a “Buy Now Pay Later” service to buy something?|
|BNPL3| In the past year, have you ever been late making a payment for something you bought using a Buy Now Pay Later service?|

**Independent variables candidates - Demographics and general questions**
|Variable name|Description| Note |
|---|---|---|
|A6|If you were to apply for a credit card today, how confident are you that your application would be approved?||
|B3|Compared to 12 months ago, would you say that you (and your family) are better off, the same, or worse off financially?||
|C4A|In the past 12 months, how frequently have you carried an unpaid balance on one or more of your credit cards?||
|I20|In the past month, would you say that your and your spouse’s or partner’s total spending was more or less than your income?||
|I41_c|In the past 12 months, have you or your spouse recieved Women, Infants, and Children (WIC) nutrition program benefits?||
|I41_e|In the past 12 months, have you or your spouse recieved free or reduced price school lunches for your children?||
|L0C|How many children do you have who are under age 18 and currently live with you?||
|ppage|Age (discrete number of years)||
|ppagecat|Age (categorical, e.g. 18-24, 25-34, etc.)|
|ppethm|Race/ethnicity|
|ppeducat|What is your highest level of eductation?|
|ppemploy|Current employment status|
|ppfs0596| What is the approximate total amount of your household's savings and investments?|
|ppfs1482|Where do you think your credit score falls?|
|pphhsize|Household size|
|ppinc7|Total household income (categorical, e.g. $10K-$24,999, $25K-$34,999)|
|ppkid017|Presence of children in the household|
|ppmarit5|Marital status||
|SL6|Are you behind on payments or in collections for one or more of the student loans from your own education?||
|EF1|Have you set aside emergency or rainy day funds that would cover your expenses for 3 months in case of sickness, job loss, economic downturn, or other emergencies?|
|EF5C|Other than any credit card bills you may have, did you pay all your bills in full last month?|Available 2023-2024 |
|EF3|

**Independent variables candidates - EF 3a-3h are responses to the following question: Suppose that you have an emergency expense that costs ($400/$500). Based on your current financial situation, how would you pay for this expense?**
|Variable name|Description|
|---|---|
|EF3_a|Put it on my credit card and pay it off in full at the next statement|
|EF3_b|Put it on my credit card and pay it off over time|
|EF3_c|With the money currently in my checking/savings account or with cash|
|EF3_d|Using money from a bank loan or line of credit|
|EF3_e|By borrowing from a friend or family member|
|EF3_f|Using a payday loan, deposit advance, or overdraft|
|EF3_g|By selling something|
|EF3_h|I wouldn't be able to pay for the expense right now|

**Independent variables candidates - X12 a-g are responses to the following question: Suppose that you have an emergency expense that costs ($400/$500). Based on your current financial situation, how would you pay for this expense?**
|Variable name|Description|
|---|---|
|EF3_a|Put it on my credit card and pay it off in full at the next statement|
|EF3_b|Put it on my credit card and pay it off over time|
|EF3_c|With the money currently in my checking/savings account or with cash|
|EF3_d|Using money from a bank loan or line of credit|
|EF3_e|By borrowing from a friend or family member|
|EF3_f|Using a payday loan, deposit advance, or overdraft|
|EF3_g|By selling something|
|EF3_h|I wouldn't be able to pay for the expense right now|

**BNPL 4a-4f are all possible responses to the following question: Thinking about the most recent time you used a Buy Now Pay Later service, why did you choose to finance the purchase in this way?**

Note: only some of these are available in the 2021 dataset. The 2021 codebook includes 4b, 4c, and 4d.
|Variable name|Description|
|---|---|
|BNPL4_a|Avoid interest charges|
|BNPL4_b|Wanted to spread out payment|
|BNPL4_c|Wanted a fixed number of payments|
|BNPL4_d|Convenience|
|BNPL4_e|Only way I could afford it|
|BNPL4_f|Only accepted payment method I had|

## Merge data sets

In [25]:
# Please add any packages here and freeze any to the requirements.txt file
import numpy as np
import pandas as pd

# Datasets as separate years
data_21 = pd.read_csv("public2021.csv")
data_22 = pd.read_csv("public2022.csv")
data_23 = pd.read_csv("public2023.csv")
data_24 = pd.read_csv("public2024.csv")

/var/folders/cr/df6gvtx90rz5bg2m0clb1gym0000gn/T/ipykernel_42345/2170642584.py:6: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  data_21 = pd.read_csv("public2021.csv")
/var/folders/cr/df6gvtx90rz5bg2m0clb1gym0000gn/T/ipykernel_42345/2170642584.py:7: DtypeWarning: Columns (16,147,149) have mixed types. Specify dtype option on import or set low_memory=False.
  data_22 = pd.read_csv("public2022.csv")
/var/folders/cr/df6gvtx90rz5bg2m0clb1gym0000gn/T/ipykernel_42345/2170642584.py:8: DtypeWarning: Columns (301,302,303) have mixed types. Specify dtype option on import or set low_memory=False.
  data_23 = pd.read_csv("public2023.csv")
/var/folders/cr/df6gvtx90rz5bg2m0clb1gym0000gn/T/ipykernel_42345/2170642584.py:9: DtypeWarning: Columns (15,41,50,100,115,117,118,119,120,121,132,151,152,153,154,182,185,186,187,188,189,190,191,192,193,194,208,209,210,211,240,250,260,261,262,263,264,265,266,301,390,391,392,394) have mixed types. Specify dtype option on import or set low_memory=False.
  data_24 = pd.read_csv("public2024.csv")

The wording and order of the BNPL variables changed between 2021 and 2022-onwards so I reordered the 2021 dataset to merge it properly with the other years.

In [26]:
# Rearranging the columns in the 2021 data to match the current survey format
data_21["BNPL4_f"] = data_21["BNPL4_d"]
data_21["BNPL4_d"] = data_21["BNPL4_b"]
data_21["BNPL4_e"] = data_21["BNPL4_c"]

# Setting columns with missing data to nan. Can undo this later if we would like the 2021 specific variables.
data_21["BNPL4_a"] = np.nan
data_21["BNPL4_b"] = np.nan
data_21["BNPL4_c"] = np.nan

In [27]:
# create columns X12_abcdefg for 21-23 datasets filling with na
# X12: financial concerns
data_21[["X12_a", "X12_b", "X12_c", "X12_d", "X12_e", "X12_f", "X12_g"]] = np.nan
data_22[["X12_a", "X12_b", "X12_c", "X12_d", "X12_e", "X12_f", "X12_g"]] = np.nan
data_23[["X12_a", "X12_b", "X12_c", "X12_d", "X12_e", "X12_f", "X12_g"]] = np.nan

In [28]:
# create columns EF5C for 21-22 datasets filling with na
# EF5C: did you pay all your bills in full last month?
data_21[["EF5C"]] = np.nan
data_22[["EF5C"]] = np.nan

In [ ]:
# LOC is a mix of str and float answers. covert all to str.
data_21['L0C'] = data_21['L0C'].apply(lambda x: str(int(x)) if isinstance(x,float) and not pd.isna(x) else x)
data_22['L0C'] = data_22['L0C'].apply(lambda x: str(int(x)) if isinstance(x,float) and not pd.isna(x) else x)
data_23['L0C'] = data_23['L0C'].apply(lambda x: str(int(x)) if isinstance(x,float) and not pd.isna(x) else x)
data_24['L0C'] = data_24['L0C'].apply(lambda x: str(int(x)) if isinstance(x,float) and not pd.isna(x) else x)

In [ ]:
# convert 5,6,7, 7 or more in 2021 and 2022 data to 5 or more to sync with 2023, 2024 data
data_21['L0C'] = data_21['L0C'].apply(lambda x: '5 or more' if x in ['5','6','7','7 or more'] else x)
data_22['L0C'] = data_22['L0C'].apply(lambda x: '5 or more' if x in ['5','6','7','7 or more'] else x)

[('2', str),
 (nan, float),
 ('1', str),
 ('3', str),
 ('5 or more', str),
 ('4', str)]

In [29]:
# Merging and exporting the dataset
datasets = [data_21, data_22, data_23, data_24]
datasets_transformed = []
years = [2021,2022,2023,2024]

# Selects relevant columns and combines datasets, organized by year
for i, dataset in enumerate(datasets):
    dataset = dataset[["BNPL1","BNPL3","BNPL4_a","BNPL4_b","BNPL4_c","BNPL4_d","BNPL4_e","BNPL4_f",
            "EF3_a","EF3_b","EF3_c","EF3_d","EF3_e","EF3_f","EF3_g","EF3_h","I20",
            "ppfs0596","ppeducat","ppage","ppagecat","ppethm","ppgender","ppinc7","ppemploy","ppmarit5","pphhsize","ppkid017", "ppfs1482",
            "SL6","B3","A6","C4A", "EF1","L0C","I41_c","I41_e",'A1_a','A1_b','A1_c','X12_a','X12_b','X12_c','X12_d','X12_e','X12_f','X12_g',
            'EF5C']]
    dataset["year"] = years[i]
    datasets_transformed.append(dataset)
data_merged = pd.concat(datasets_transformed)

/var/folders/cr/df6gvtx90rz5bg2m0clb1gym0000gn/T/ipykernel_42345/2015482858.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset["year"] = years[i]
/var/folders/cr/df6gvtx90rz5bg2m0clb1gym0000gn/T/ipykernel_42345/2015482858.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset["year"] = years[i]
/var/folders/cr/df6gvtx90rz5bg2m0clb1gym0000gn/T/ipykernel_42345/2015482858.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset["year"] = years[i]
/var/folders/cr/df6gvtx90rz5bg2m0clb1gym0000gn/T/ipykernel_42345/2015482858.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset["year"] = years[i]

In [30]:
# Export
display(data_merged)
data_merged.to_csv("data_merged.csv")

,BNPL1,BNPL3,BNPL4_a,BNPL4_b,BNPL4_c,BNPL4_d,BNPL4_e,BNPL4_f,EF3_a,EF3_b,...,A1_c,X12_a,X12_b,X12_c,X12_d,X12_e,X12_f,X12_g,EF5C,year
0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Put it on my credit card and pay it off in ful...,No,...,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021
1,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Put it on my credit card and pay it off in ful...,No,...,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021
2,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021
3,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Put it on my credit card and pay it off in ful...,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021
4,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,Put it on my credit card and pay it off over time,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12290,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,No,...,Yes,Major concern,Major concern,Major concern,Major concern,Major concern,Major concern,Minor concern,No,2024
12291,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,No,...,NaN,Not a concern,Major concern,Major concern,Major concern,Minor concern,Not a concern,Not a concern,Yes,2024
12292,Yes,No,Yes,Yes,Yes,Yes,Yes,Yes,No,Yes,...,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,2024
12293,Yes,Yes,No,Yes,Yes,Yes,Yes,Yes,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,2024
12294,Yes,Yes,No,Yes,Yes,No,Yes,No,Yes,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,2024

## Sanity check

In [41]:
# check unique values in each question
data_check = []
data_2024 = data_merged[data_merged['year'] == 2024]
data_2023 = data_merged[data_merged['year'] == 2023]
data_2022 = data_merged[data_merged['year'] == 2022]
data_2021 = data_merged[data_merged['year'] == 2021]

for c in data_merged.columns:
    data_check.append({'column': c,
                    '2024 unique values': data_2024[c].unique(),
                    '2023 unique values': data_2023[c].unique(),
                    '2022 unique values': data_2022[c].unique(),
                    '2021 unique values': data_2021[c].unique(),
                    })
pd.DataFrame(data_check)

,column,2024 unique values,2023 unique values,2022 unique values,2021 unique values
0,BNPL1,"[No, Yes]","[No, Yes]","[No, Yes]","[No, Yes]"
1,BNPL3,"[nan, No, Yes]","[nan, No, Yes]","[nan, No, Yes]","[nan, No, Yes]"
2,BNPL4_a,"[nan, No, Yes]","[nan, No, Yes]","[nan, Yes, No]",[nan]
3,BNPL4_b,"[nan, Yes, No]","[nan, Yes, No]","[nan, Yes, No]",[nan]
4,BNPL4_c,"[nan, Yes, No]","[nan, Yes, No]","[nan, Yes, No]",[nan]
5,BNPL4_d,"[nan, Yes, No]","[nan, Yes, No]","[nan, Yes, No]","[nan, No, Yes]"
6,BNPL4_e,"[nan, Yes, No]","[nan, No, Yes]","[nan, No, Yes]","[nan, Yes, No]"
7,BNPL4_f,"[nan, No, Yes]","[nan, No, Yes]","[nan, No, Yes]","[nan, No, Yes]"
8,EF3_a,"[Yes, No]",[Put it on my credit card and pay it off in fu...,[Put it on my credit card and pay it off in fu...,[Put it on my credit card and pay it off in fu...
9,EF3_b,"[No, Yes]","[No, did not do this, Put it on my credit card...","[No, Put it on my credit card and pay it off o...","[No, Put it on my credit card and pay it off o..."
10,EF3_c,"[No, Yes]","[No, did not do this, With the money currently...","[No, With the money currently in my checking/s...","[No, With the money currently in my checking/s..."
11,EF3_d,"[No, Yes]","[No, did not do this, Using money from a bank ...","[No, Using money from a bank loan or line of c...","[No, Using money from a bank loan or line of c..."
12,EF3_e,"[No, Yes]","[No, did not do this, By borrowing from a frie...","[No, By borrowing from a friend or family member]","[No, By borrowing from a friend or family member]"
13,EF3_f,"[No, Yes]","[No, did not do this, Using a payday loan, dep...","[No, Using a payday loan, deposit advance, or ...","[No, Using a payday loan, deposit advance, or ..."
14,EF3_g,"[No, Yes]","[No, did not do this, By selling something]","[No, By selling something]","[No, By selling something]"
15,EF3_h,"[No, Yes]","[No, did not do this, I wouldn’t be able to pa...","[No, I wouldn’t be able to pay for the expense...","[No, I wouldn’t be able to pay for the expense..."
16,I20,"[Less than your income, More than your income,...","[The same as your income, Less than your incom...","[Less than your income, More than your income,...","[The same as your income, More than your incom..."
17,ppfs0596,"[Under $50,000, nan, $50,000 - $99,999, $1,000...","[Under $50,000, $100,000 - $249,999, $50,000 -...","[Under $50,000, $250,000 - $499,999, $100,000 ...","[$50,000 - $99,999, Not sure, Under $50,000, n..."
18,ppeducat,"[Bachelor's degree or higher, High school grad...","[Bachelor's degree or higher, Some college or ...","[Bachelor's degree or higher, Some college or ...","[Bachelor's degree or higher, High school grad..."
19,ppage,"[82, 79, 61, 67, 59, 65, 62, 80, 47, 77, 84, 7...","[81, 82, 86, 59, 57, 77, 60, 78, 76, 63, 64, 7...","[80, 77, 54, 92, 69, 53, 56, 59, 57, 72, 63, 7...","[54, 56, 76, 69, 62, 61, 66, 82, 79, 71, 89, 8..."
20,ppagecat,"[75+, 55-64, 65-74, 45-54, 18-24, 25-34, 35-44]","[75+, 55-64, 65-74, 45-54, 35-44, 18-24, 25-34]","[75+, 45-54, 65-74, 55-64, 35-44, 18-24, 25-34]","[45-54, 55-64, 75+, 65-74, 25-34, 35-44, 18-24]"
21,ppethm,"[White, Non-Hispanic, 2+ Races, Non-Hispanic, ...","[White, Non-Hispanic, 2+ Races, Non-Hispanic, ...","[White, Non-Hispanic, Hispanic, Black, Non-His...","[White, Non-Hispanic, Other, Non-Hispanic, 2+ ..."
22,ppgender,"[Female, Male]","[Female, Male]","[Female, Male]","[Male, Female]"
23,ppinc7,"[$25,000 to $49,999, $100,000 to $149,999, $50...","[$25,000 to $49,999, $50,000 to $74,999, $100,...","[$25,000 to $49,999, $150,000 or more, $100,00...","[$100,000 to $149,999, $75,000 to $99,999, $25..."
24,ppemploy,"[Working part-time, Not working, Working full-...","[Working part-time, Not working, Working full-...","[Working part-time, Not working, Working full-...","[Working full-time, Working part-time, Not wor..."
25,ppmarit5,"[Never married, Divorced, Now married, Widowed...","[Never married, Now married, Divorced, Widowed...","[Never married, Divorced, Widowed, Now married...","[Now married, Widowed, Divorced, Never married..."
26,pphhsize,"[1, 2, 3, 8, 6, 4, 10, 5, 7, 9]","[1, 2, 3, 4, 10, 6, 5, 8, 7, 9]","[1, 3, 2, 8, 4, 6, 10, 5, 7, 9]","[4, 1, 2, 8, 3, 5, 9, 6, 7, 10]"
27,ppkid017,"[0, 1, 3, 2, 5, 4, 6, 9, 8, 7]","[0, 1, 2, 3, 5, 4, 6, 8, 7]","[0, 1, 2, 3, 5, 7, 4, 6, 9, 8]","[2, 0, 1, 3, 4, 6, 5, 9, 8, 7]"
28,ppfs1482,"[Excellent, Don’t know, Good, Fair, Poor, nan,...","[Excellent, Don’t know, Good, Fair, nan, Very ...","[Excellent, Good, Fair, nan, Don’t know, Poor,...","[Excellent, nan, Good, Poor, Fair, Don’t know,..."
29,SL6,"[nan, No, Yes]","[nan, No, Yes]","[nan, Yes, No]","[nan, No, Yes]"
30,B3,"[Somewhat better off, About the same, Somewhat...","[About the same, Somewhat worse off, Much bett...","[Much better off, About the same, Somewhat wor...","[About the same, Somewhat worse off, Somewhat ..."
31,A6,"[Very confident, Don’t know, Somewhat confiden...","[Very confident, Somewhat confident, Not confi...","[Very confident, Somewhat confident, Not confi...","[Very confident, Not confident, Somewhat confi..."
32,C4A,[Never carried an unpaid balance (always pay i...,[Never carried an unpaid balance (always pay i...,[Never carried an unpaid balance (always pay i...,[Never carried an unpaid balance (always pay i...
33,EF1,"[Yes, No]","[Yes, No]","[Yes, No]","[Yes, No]"
34,L0C,"[nan, 2, 5 or more, 1, 3, 4, 4.0]","[nan, 1, 2, 5 or more, 3, 4]","[nan, 1.0, 2.0, 6.0, 3.0, 4.0, 5.0, 1, 2, 3, 4...","[2, nan, 1, 3, 7 or more, 5, 4, 1.0, 3.0, 2.0,..."
35,I41_c,"[No, Yes]","[No, Yes]","[nan, No, Yes]","[No, nan, Yes]"
36,I41_e,"[nan, No, Yes]","[nan, Yes, No]","[nan, Yes, No]","[No, nan, Yes]"
37,A1_a,"[nan, No, Yes]","[No, nan, Yes]","[nan, No, Yes]","[No, Yes, nan]"
38,A1_b,"[nan, No, Yes]","[No, nan, Yes]","[nan, No, Yes]","[No, nan, Yes]"
39,A1_c,"[nan, No, Yes]","[No, nan, Yes]","[nan, No, Yes]","[No, nan, Yes]"
40,X12_a,"[nan, Not a concern, Major concern, Minor conc...",[nan],[nan],[nan]
41,X12_b,"[nan, Not a concern, Major concern, Minor conc...",[nan],[nan],[nan]
42,X12_c,"[nan, Not a concern, Major concern, Minor conc...",[nan],[nan],[nan]
43,X12_d,"[nan, Not a concern, Major concern, Minor conc...",[nan],[nan],[nan]
44,X12_e,"[nan, Not a concern, Major concern, Minor conc...",[nan],[nan],[nan]
45,X12_f,"[nan, Not a concern, Major concern, Minor conc...",[nan],[nan],[nan]
46,X12_g,"[nan, Not a concern, Major concern, Minor conc...",[nan],[nan],[nan]
47,EF5C,"[Yes, No]","[No, Yes]",[nan],[nan]
48,year,[2024],[2023],[2022],[2021]