## Codebook
-----------
Here are all of the variables shared across the four surveys. I verified that the codes correspond to the same questions in each version. Some items, such as BNPL 4 represent multiple responses to a single question and thus take up more than one column.

**Dependent variables**
|BNPL1| In the past year, have you used a “Buy Now Pay Later” service to buy something?|
|BNPL3| In the past year, have you ever been late making a payment for something you bought using a Buy Now Pay Later service?|

**Independent variables candidates - Demographics and general questions**
|Variable name|Description| Note |
|---|---|---|
|A6|If you were to apply for a credit card today, how confident are you that your application would be approved?||
|B3|Compared to 12 months ago, would you say that you (and your family) are better off, the same, or worse off financially?||
|C4A|In the past 12 months, how frequently have you carried an unpaid balance on one or more of your credit cards?||
|I20|In the past month, would you say that your and your spouse’s or partner’s total spending was more or less than your income?||
|I41_c|In the past 12 months, have you or your spouse recieved Women, Infants, and Children (WIC) nutrition program benefits?||
|I41_e|In the past 12 months, have you or your spouse recieved free or reduced price school lunches for your children?||
|L0C|How many children do you have who are under age 18 and currently live with you?||
|ppage|Age (discrete number of years)||
|ppagecat|Age (categorical, e.g. 18-24, 25-34, etc.)|
|ppethm|Race/ethnicity|
|ppeducat|What is your highest level of eductation?|
|ppemploy|Current employment status|
|ppfs0596| What is the approximate total amount of your household's savings and investments?|
|ppfs1482|Where do you think your credit score falls?|
|pphhsize|Household size|
|ppinc7|Total household income (categorical, e.g. $10K-$24,999, $25K-$34,999)|
|ppkid017|Presence of children in the household|
|ppmarit5|Marital status||
|SL6|Are you behind on payments or in collections for one or more of the student loans from your own education?||
|EF1|Have you set aside emergency or rainy day funds that would cover your expenses for 3 months in case of sickness, job loss, economic downturn, or other emergencies?|
|EF5C|Other than any credit card bills you may have, did you pay all your bills in full last month?|Available 2023-2024 |
|EF3|

**Independent variables candidates - EF 3a-3h are responses to the following question: Suppose that you have an emergency expense that costs ($400/$500). Based on your current financial situation, how would you pay for this expense?**
|Variable name|Description|
|---|---|
|EF3_a|Put it on my credit card and pay it off in full at the next statement|
|EF3_b|Put it on my credit card and pay it off over time|
|EF3_c|With the money currently in my checking/savings account or with cash|
|EF3_d|Using money from a bank loan or line of credit|
|EF3_e|By borrowing from a friend or family member|
|EF3_f|Using a payday loan, deposit advance, or overdraft|
|EF3_g|By selling something|
|EF3_h|I wouldn't be able to pay for the expense right now|

**Independent variables candidates - X12 a-g are responses to the following question: Suppose that you have an emergency expense that costs ($400/$500). Based on your current financial situation, how would you pay for this expense?**
|Variable name|Description|
|---|---|
|EF3_a|Put it on my credit card and pay it off in full at the next statement|
|EF3_b|Put it on my credit card and pay it off over time|
|EF3_c|With the money currently in my checking/savings account or with cash|
|EF3_d|Using money from a bank loan or line of credit|
|EF3_e|By borrowing from a friend or family member|
|EF3_f|Using a payday loan, deposit advance, or overdraft|
|EF3_g|By selling something|
|EF3_h|I wouldn't be able to pay for the expense right now|

**BNPL 4a-4f are all possible responses to the following question: Thinking about the most recent time you used a Buy Now Pay Later service, why did you choose to finance the purchase in this way?**

Note: only some of these are available in the 2021 dataset. The 2021 codebook includes 4b, 4c, and 4d.
|Variable name|Description|
|---|---|
|BNPL4_a|Avoid interest charges|
|BNPL4_b|Wanted to spread out payment|
|BNPL4_c|Wanted a fixed number of payments|
|BNPL4_d|Convenience|
|BNPL4_e|Only way I could afford it|
|BNPL4_f|Only accepted payment method I had|

## Merge data sets

In [45]:
# Please add any packages here and freeze any to the requirements.txt file
import numpy as np
import pandas as pd

# Datasets as separate years
data_21 = pd.read_csv("data/public2021.csv")
data_22 = pd.read_csv("data/public2022.csv")
data_23 = pd.read_csv("data/public2023.csv")
data_24 = pd.read_csv("data/public2024.csv")

C:\Users\yyork\AppData\Local\Temp\ipykernel_7300\4123913040.py:6: DtypeWarning: Columns (0: L0C) have mixed types. Specify dtype option on import or set low_memory=False.
  data_21 = pd.read_csv("data/public2021.csv")
C:\Users\yyork\AppData\Local\Temp\ipykernel_7300\4123913040.py:7: DtypeWarning: Columns (0: L0C, 1: A8_c, 2: A8_e) have mixed types. Specify dtype option on import or set low_memory=False.
  data_22 = pd.read_csv("data/public2022.csv")
C:\Users\yyork\AppData\Local\Temp\ipykernel_7300\4123913040.py:8: DtypeWarning: Columns (0: ppfs0001, 1: ppfs0596, 2: ppfs1482) have mixed types. Specify dtype option on import or set low_memory=False.
  data_23 = pd.read_csv("data/public2023.csv")
C:\Users\yyork\AppData\Local\Temp\ipykernel_7300\4123913040.py:9: DtypeWarning: Columns (0: L0C, 1: CG1A, 2: CG9, 3: D41_b, 4: GE1C, 5: GE1E_a, 6: GE1E_b, 7: GE1E_c, 8: GE1E_d, 9: GE1E_e, 10: GH12A, 11: R5C_a, 12: R5C_b, 13: R5C_c, 14: R5C_d, 15: BK48, 16: BK50, 17: BK51, 18: BK52_a, 19: BK52_b, 20: BK52_c, 21: BK52_d, 22: BK52_e, 23: BK52_f, 24: BK52_g, 25: BK52_h, 26: A8_b, 27: A8_c, 28: A8_d, 29: A8_e, 30: SL4, 31: SL13, 32: K14_a, 33: K14_b, 34: K15_a, 35: K15_b, 36: K15_c, 37: K15_d, 38: K15_e, 39: INF3_g, 40: ppfs0001, 41: ppfs0596, 42: ppfs1482, 43: pphi0001) have mixed types. Specify dtype option on import or set low_memory=False.
  data_24 = pd.read_csv("data/public2024.csv")

The wording and order of the BNPL variables changed between 2021 and 2022-onwards so I reordered the 2021 dataset to merge it properly with the other years.

In [46]:
# Rearranging the columns in the 2021 data to match the current survey format
data_21["BNPL4_f"] = data_21["BNPL4_d"]
data_21["BNPL4_d"] = data_21["BNPL4_b"]
data_21["BNPL4_e"] = data_21["BNPL4_c"]

# Setting columns with missing data to nan. Can undo this later if we would like the 2021 specific variables.
data_21["BNPL4_a"] = np.nan
data_21["BNPL4_b"] = np.nan
data_21["BNPL4_c"] = np.nan

In [47]:
# create columns X12_abcdefg for 21-23 datasets filling with na
# X12: financial concerns
data_21[["X12_a", "X12_b", "X12_c", "X12_d", "X12_e", "X12_f", "X12_g"]] = np.nan
data_22[["X12_a", "X12_b", "X12_c", "X12_d", "X12_e", "X12_f", "X12_g"]] = np.nan
data_23[["X12_a", "X12_b", "X12_c", "X12_d", "X12_e", "X12_f", "X12_g"]] = np.nan

C:\Users\yyork\AppData\Local\Temp\ipykernel_7300\1264105312.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data_21[["X12_a", "X12_b", "X12_c", "X12_d", "X12_e", "X12_f", "X12_g"]] = np.nan
C:\Users\yyork\AppData\Local\Temp\ipykernel_7300\1264105312.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data_22[["X12_a", "X12_b", "X12_c", "X12_d", "X12_e", "X12_f", "X12_g"]] = np.nan
C:\Users\yyork\AppData\Local\Temp\ipykernel_7300\1264105312.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data_23[["X12_a", "X12_b", "X12_c", "X12_d", "X12_e", "X12_f", "X12_g"]] = np.nan

In [48]:
# create columns EF5C for 21-22 datasets filling with na
# EF5C: did you pay all your bills in full last month?
data_21[["EF5C"]] = np.nan
data_22[["EF5C"]] = np.nan

C:\Users\yyork\AppData\Local\Temp\ipykernel_7300\712855912.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data_21[["EF5C"]] = np.nan
C:\Users\yyork\AppData\Local\Temp\ipykernel_7300\712855912.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data_22[["EF5C"]] = np.nan

In [49]:
# LOC is a mix of str and float answers. covert all to str.
data_21['L0C'] = data_21['L0C'].apply(lambda x: str(int(x)) if isinstance(x,float) and not pd.isna(x) else x)
data_22['L0C'] = data_22['L0C'].apply(lambda x: str(int(x)) if isinstance(x,float) and not pd.isna(x) else x)
data_23['L0C'] = data_23['L0C'].apply(lambda x: str(int(x)) if isinstance(x,float) and not pd.isna(x) else x)
data_24['L0C'] = data_24['L0C'].apply(lambda x: str(int(x)) if isinstance(x,float) and not pd.isna(x) else x)

In [50]:
# convert 5,6,7, 7 or more in 2021 and 2022 data to 5 or more to sync with 2023, 2024 data
data_21['L0C'] = data_21['L0C'].apply(lambda x: '5 or more' if x in ['5','6','7','7 or more'] else x)
data_22['L0C'] = data_22['L0C'].apply(lambda x: '5 or more' if x in ['5','6','7','7 or more'] else x)

In [51]:
# convert EF3_abcdefgh values to be consistent across years
mapping = {
  'Put it on my credit card and pay it off in full at the next statement': 'Yes',
  'Put it on my credit card and pay it off over time': 'Yes',
  'With the money currently in my checking/savings account or with cash': 'Yes',
  'Using money from a bank loan or line of credit': 'Yes',
  'By borrowing from a friend or family member': 'Yes',
  'Using a payday loan, deposit advance, or overdraft':'Yes',
  'By selling something': 'Yes',
  "I wouldn’t be able to pay for the expense right now": 'Yes',
  'No, did not do this': 'No'
}

cols = ["EF3_a", "EF3_b", "EF3_c", "EF3_d", "EF3_e", "EF3_f", "EF3_g", "EF3_h"]
data_21[cols] = data_21[cols].apply(lambda col: col.map(mapping))
data_22[cols] = data_22[cols].apply(lambda col: col.map(mapping))
data_23[cols] = data_23[cols].apply(lambda col: col.map(mapping))
#data_24[cols] = data_24[cols].apply(lambda col: col.map(mapping))

In [52]:
# Merging and exporting the dataset
datasets = [data_21, data_22, data_23, data_24]
datasets_transformed = []
years = [2021,2022,2023,2024]

# Selects relevant columns and combines datasets, organized by year
for i, dataset in enumerate(datasets):
    dataset = dataset[["weight","BNPL1","BNPL3","BNPL4_a","BNPL4_b","BNPL4_c","BNPL4_d","BNPL4_e","BNPL4_f",
            "EF3_a","EF3_b","EF3_c","EF3_d","EF3_e","EF3_f","EF3_g","EF3_h","I20",
            "ppfs0596","ppeducat","ppage","ppagecat","ppethm","ppgender","ppinc7","ppemploy","ppmarit5","pphhsize","ppkid017", "ppfs1482",
            "SL6","B3","A6","C4A", "EF1","L0C","I41_c","I41_e",'A1_a','A1_b','A1_c','X12_a','X12_b','X12_c','X12_d','X12_e','X12_f','X12_g',
            'EF5C']]
    dataset["year"] = years[i]
    datasets_transformed.append(dataset)
data_merged = pd.concat(datasets_transformed)

In [53]:
# Export
display(data_merged)
data_merged.to_csv("data/data_merged.csv")

,weight,BNPL1,BNPL3,BNPL4_a,BNPL4_b,BNPL4_c,BNPL4_d,BNPL4_e,BNPL4_f,EF3_a,...,A1_c,X12_a,X12_b,X12_c,X12_d,X12_e,X12_f,X12_g,EF5C,year
0,0.5404,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,...,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021
1,0.7613,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,...,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021
2,0.7890,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021
3,0.5585,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021
4,0.8362,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12290,1.1731,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,...,Yes,Major concern,Major concern,Major concern,Major concern,Major concern,Major concern,Minor concern,No,2024
12291,0.8212,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,...,NaN,Not a concern,Major concern,Major concern,Major concern,Minor concern,Not a concern,Not a concern,Yes,2024
12292,1.1841,Yes,No,Yes,Yes,Yes,Yes,Yes,Yes,No,...,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,2024
12293,1.0517,Yes,Yes,No,Yes,Yes,Yes,Yes,Yes,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,2024
12294,2.6505,Yes,Yes,No,Yes,Yes,No,Yes,No,Yes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,2024

## Sanity check

In [54]:
# check unique values in each question
data_check = []
data_2024 = data_merged[data_merged['year'] == 2024]
data_2023 = data_merged[data_merged['year'] == 2023]
data_2022 = data_merged[data_merged['year'] == 2022]
data_2021 = data_merged[data_merged['year'] == 2021]

for c in data_merged.columns:
    data_check.append({'column': c,
                    '2024 unique values': data_2024[c].unique(),
                    '2023 unique values': data_2023[c].unique(),
                    '2022 unique values': data_2022[c].unique(),
                    '2021 unique values': data_2021[c].unique(),
                    })
pd.DataFrame(data_check)

,column,2024 unique values,2023 unique values,2022 unique values,2021 unique values
0,weight,"[0.6149, 0.8301, 0.4447, 0.8333, 0.9064, 1.247...","[0.5468, 0.6107, 0.4587, 1.3732, 0.9264, 0.714...","[0.5503, 0.9869, 0.9167, 0.9967, 0.6357, 0.901...","[0.5404, 0.7613, 0.789, 0.5585, 0.8362, 0.7032..."
1,BNPL1,"[No, Yes]","[No, Yes]","[No, Yes]","[No, Yes]"
2,BNPL3,"[nan, No, Yes]","[nan, No, Yes]","[nan, No, Yes]","[nan, No, Yes]"
3,BNPL4_a,"[nan, No, Yes]","[nan, No, Yes]","[nan, Yes, No]",[nan]
4,BNPL4_b,"[nan, Yes, No]","[nan, Yes, No]","[nan, Yes, No]",[nan]
5,BNPL4_c,"[nan, Yes, No]","[nan, Yes, No]","[nan, Yes, No]",[nan]
6,BNPL4_d,"[nan, Yes, No]","[nan, Yes, No]","[nan, Yes, No]","[nan, No, Yes]"
7,BNPL4_e,"[nan, Yes, No]","[nan, No, Yes]","[nan, No, Yes]","[nan, Yes, No]"
8,BNPL4_f,"[nan, No, Yes]","[nan, No, Yes]","[nan, No, Yes]","[nan, No, Yes]"
9,EF3_a,"[Yes, No]","[Yes, No]","[Yes, nan]","[Yes, nan]"
10,EF3_b,"[No, Yes]","[No, Yes]","[nan, Yes]","[nan, Yes]"
11,EF3_c,"[No, Yes]","[No, Yes]","[nan, Yes]","[nan, Yes]"
12,EF3_d,"[No, Yes]","[No, Yes]","[nan, Yes]","[nan, Yes]"
13,EF3_e,"[No, Yes]","[No, Yes]","[nan, Yes]","[nan, Yes]"
14,EF3_f,"[No, Yes]","[No, Yes]","[nan, Yes]","[nan, Yes]"
15,EF3_g,"[No, Yes]","[No, Yes]","[nan, Yes]","[nan, Yes]"
16,EF3_h,"[No, Yes]","[No, Yes]","[nan, Yes]","[nan, Yes]"
17,I20,"[Less than your income, More than your income,...","[The same as your income, Less than your incom...","[Less than your income, More than your income,...","[The same as your income, More than your incom..."
18,ppfs0596,"[Under $50,000, nan, $50,000 - $99,999, $1,000...","[Under $50,000, $100,000 - $249,999, $50,000 -...","[Under $50,000, $250,000 - $499,999, $100,000 ...","[$50,000 - $99,999, Not sure, Under $50,000, n..."
19,ppeducat,"[Bachelor's degree or higher, High school grad...","[Bachelor's degree or higher, Some college or ...","[Bachelor's degree or higher, Some college or ...","[Bachelor's degree or higher, High school grad..."
20,ppage,"[82, 79, 61, 67, 59, 65, 62, 80, 47, 77, 84, 7...","[81, 82, 86, 59, 57, 77, 60, 78, 76, 63, 64, 7...","[80, 77, 54, 92, 69, 53, 56, 59, 57, 72, 63, 7...","[54, 56, 76, 69, 62, 61, 66, 82, 79, 71, 89, 8..."
21,ppagecat,"[75+, 55-64, 65-74, 45-54, 18-24, 25-34, 35-44]","[75+, 55-64, 65-74, 45-54, 35-44, 18-24, 25-34]","[75+, 45-54, 65-74, 55-64, 35-44, 18-24, 25-34]","[45-54, 55-64, 75+, 65-74, 25-34, 35-44, 18-24]"
22,ppethm,"[White, Non-Hispanic, 2+ Races, Non-Hispanic, ...","[White, Non-Hispanic, 2+ Races, Non-Hispanic, ...","[White, Non-Hispanic, Hispanic, Black, Non-His...","[White, Non-Hispanic, Other, Non-Hispanic, 2+ ..."
23,ppgender,"[Female, Male]","[Female, Male]","[Female, Male]","[Male, Female]"
24,ppinc7,"[$25,000 to $49,999, $100,000 to $149,999, $50...","[$25,000 to $49,999, $50,000 to $74,999, $100,...","[$25,000 to $49,999, $150,000 or more, $100,00...","[$100,000 to $149,999, $75,000 to $99,999, $25..."
25,ppemploy,"[Working part-time, Not working, Working full-...","[Working part-time, Not working, Working full-...","[Working part-time, Not working, Working full-...","[Working full-time, Working part-time, Not wor..."
26,ppmarit5,"[Never married, Divorced, Now married, Widowed...","[Never married, Now married, Divorced, Widowed...","[Never married, Divorced, Widowed, Now married...","[Now married, Widowed, Divorced, Never married..."
27,pphhsize,"[1, 2, 3, 8, 6, 4, 10, 5, 7, 9]","[1, 2, 3, 4, 10, 6, 5, 8, 7, 9]","[1, 3, 2, 8, 4, 6, 10, 5, 7, 9]","[4, 1, 2, 8, 3, 5, 9, 6, 7, 10]"
28,ppkid017,"[0, 1, 3, 2, 5, 4, 6, 9, 8, 7]","[0, 1, 2, 3, 5, 4, 6, 8, 7]","[0, 1, 2, 3, 5, 7, 4, 6, 9, 8]","[2, 0, 1, 3, 4, 6, 5, 9, 8, 7]"
29,ppfs1482,"[Excellent, Don’t know, Good, Fair, Poor, nan,...","[Excellent, Don’t know, Good, Fair, nan, Very ...","[Excellent, Good, Fair, nan, Don’t know, Poor,...","[Excellent, nan, Good, Poor, Fair, Don’t know,..."
30,SL6,"[nan, No, Yes]","[nan, No, Yes]","[nan, Yes, No]","[nan, No, Yes]"
31,B3,"[Somewhat better off, About the same, Somewhat...","[About the same, Somewhat worse off, Much bett...","[Much better off, About the same, Somewhat wor...","[About the same, Somewhat worse off, Somewhat ..."
32,A6,"[Very confident, Don’t know, Somewhat confiden...","[Very confident, Somewhat confident, Not confi...","[Very confident, Somewhat confident, Not confi...","[Very confident, Not confident, Somewhat confi..."
33,C4A,[Never carried an unpaid balance (always pay i...,[Never carried an unpaid balance (always pay i...,[Never carried an unpaid balance (always pay i...,[Never carried an unpaid balance (always pay i...
34,EF1,"[Yes, No]","[Yes, No]","[Yes, No]","[Yes, No]"
35,L0C,"[nan, 2, 5 or more, 1, 3, 4]","[nan, 1, 2, 5 or more, 3, 4]","[nan, 1, 2, 5 or more, 3, 4]","[2, nan, 1, 3, 5 or more, 4]"
36,I41_c,"[No, Yes]","[No, Yes]","[nan, No, Yes]","[No, nan, Yes]"
37,I41_e,"[nan, No, Yes]","[nan, Yes, No]","[nan, Yes, No]","[No, nan, Yes]"
38,A1_a,"[nan, No, Yes]","[No, nan, Yes]","[nan, No, Yes]","[No, Yes, nan]"
39,A1_b,"[nan, No, Yes]","[No, nan, Yes]","[nan, No, Yes]","[No, nan, Yes]"
40,A1_c,"[nan, No, Yes]","[No, nan, Yes]","[nan, No, Yes]","[No, nan, Yes]"
41,X12_a,"[nan, Not a concern, Major concern, Minor conc...",[nan],[nan],[nan]
42,X12_b,"[nan, Not a concern, Major concern, Minor conc...",[nan],[nan],[nan]
43,X12_c,"[nan, Not a concern, Major concern, Minor conc...",[nan],[nan],[nan]
44,X12_d,"[nan, Not a concern, Major concern, Minor conc...",[nan],[nan],[nan]
45,X12_e,"[nan, Not a concern, Major concern, Minor conc...",[nan],[nan],[nan]
46,X12_f,"[nan, Not a concern, Major concern, Minor conc...",[nan],[nan],[nan]
47,X12_g,"[nan, Not a concern, Major concern, Minor conc...",[nan],[nan],[nan]
48,EF5C,"[Yes, No]","[No, Yes]",[nan],[nan]
49,year,[2024],[2023],[2022],[2021]